/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.gov.pagopa.bpd.io_backend.api.pagopa;

import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import it.gov.pagopa.bpd.io_backend.model.wallets.dto.pagopa.WalletNPInputV2;
import it.gov.pagopa.bpd.io_backend.model.wallets.resource.pagopa.WalletNPResource;
import it.gov.pagopa.bpd.io_backend.model.wallets.resource.pagopa.WalletNPResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

@Validated
public interface WalletsApiV2 {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /wallets/np-wallets : Create new NP Wallet resource
     *
     * @param body  (required)
     * @return Resource NP Wallet created (status code 201)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Create new NP Wallet resource", nickname = "createWalletNP", notes = "", response = WalletNPResource.class, tags={ "np-wallets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Resource NP Wallet created", response = WalletNPResource.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @PostMapping(
        value = "/wallets/np-wallets",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<WalletNPResource> createWalletNP(@ApiParam(value = "" ,required=true )  @Valid @RequestBody WalletNPInputV2 body);


    /**
     * GET /wallets/np-wallets/get-wallets/{fiscalCode} : Retrieves user&#39;s RTD instruments list
     *
     * @param fiscalCode user&#39;s fiscal code (required)
     * @return User&#39;s RTD wallets list (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @ApiOperation(value = "Retrieves user's RTD instruments list", nickname = "getUserRtdWallets", notes = "", response = WalletNPResponse.class, responseContainer = "List", tags={ "np-wallets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "User's RTD wallets list", response = WalletNPResponse.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Not Found"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @GetMapping(
        value = "/wallets/np-wallets/get-wallets/{fiscalCode}",
        produces = { "application/json" }
    )
    ResponseEntity<List<WalletNPResponse>> getUserRtdWallets(@ApiParam(value = "user's fiscal code",required=true) @PathVariable("fiscalCode") String fiscalCode);

}
