server:
  port: 8080
  contextPath: /

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

logging:
  level:
    root: INFO
    it.gov.pagopa.bpd: DEBUG

bpd:
  hash:
    salt: ${BPD_HASH_SALT:SALT123}
  jwt:
    key: ${BPD_JWT_KEY:}
