server:
  port: 8080
  contextPath: /

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

logging:
  level:
    root: DEBUG

bpd:
  hash:
    salt: ${BPD_HASH_SALT:abcde12345}
  jwt:
    key: ${BPD_JWT_KEY:}
