apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstariobackendtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cstariobackendtest
  template:
    metadata:
      labels:
        app: cstariobackendtest
    spec:
      containers:
        - resources:
            limits:
              cpu: 1000m
              memory: 4Gi
          name: cstariobackendtest
          image: cstaruatregistry.azurecr.io/cstariobackendtest
          ports:
            - containerPort: 8080
          env:
            - name: BPD_JWT_KEY
              value: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
          envFrom:
            - configMapRef:
                name: cstariobackendtest
                optional: true